In [1]:
%load_ext autoreload
%autoreload 2

In [15]:
from kooplearn.abc import ContextWindow, ContextWindowDataset
from kooplearn.data import TensorContextDataset, TrajectoryContextDataset

import numpy as np
import torch

In [16]:
traj_np = np.arange(20)
traj_torch = torch.arange(20)

In [17]:
ctx = TrajectoryContextDataset(traj_torch, context_length=5)

In [20]:
ctx[[0, 1]]

TensorContextDataset <item_count=2, context_length=5, data=[[[0]
  [1]
  [2]
  [3]
  [4]]

 [[1]
  [2]
  [3]
  [4]
  [5]]]>

In [14]:
ctx[[1,2]].lookback(5)

TypeError: can only concatenate list (not "int") to list

In [10]:
ctx.lookback(1)

array([[[ 0]],

       [[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]],

       [[12]],

       [[13]],

       [[14]],

       [[15]]])

In [18]:
test_single_window[3]

3

In [3]:
clipped_out = np.take(contexts.trajectory, contexts.idx_map + 1, axis=0, mode='clip')
np.place(clipped_out, ~(contexts.idx_map + 1 < len(contexts.trajectory)), np.NAN)

NameError: name 'np' is not defined

In [53]:
clipped_out

array([[[ 1.],
        [ 3.],
        [ 5.]],

       [[ 2.],
        [ 4.],
        [ 6.]],

       [[ 3.],
        [ 5.],
        [ 7.]],

       [[ 4.],
        [ 6.],
        [ 8.]],

       [[ 5.],
        [ 7.],
        [ 9.]],

       [[ 6.],
        [ 8.],
        [10.]],

       [[ 7.],
        [ 9.],
        [11.]],

       [[ 8.],
        [10.],
        [12.]],

       [[ 9.],
        [11.],
        [13.]],

       [[10.],
        [12.],
        [14.]],

       [[11.],
        [13.],
        [15.]],

       [[12.],
        [14.],
        [16.]],

       [[13.],
        [15.],
        [17.]],

       [[14.],
        [16.],
        [18.]],

       [[15.],
        [17.],
        [19.]],

       [[16.],
        [18.],
        [nan]]], dtype=float32)

In [11]:
ctx.data.shape

torch.Size([16, 5, 1])