In [52]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [60]:
from kooplearn.abc import ContextWindow, ContextWindowDataset
from kooplearn.data import TensorContextDataset

import numpy as np
import torch

In [65]:
ctx_np = np.arange(20).reshape(4, 5, 1)
ctx_torch = torch.arange(20).reshape(4, 5, 1)

In [74]:
TensorContextDataset(ctx_torch).lookforward(2).shape

torch.Size([4, 3, 1])

In [69]:
ctx_np

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]],

       [[15],
        [16],
        [17],
        [18],
        [19]]])

In [51]:
print(test_ctxs)

ContextWindowDataset <item_count=10, context_length=5, data=[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]>


In [18]:
test_single_window[3]

3

In [3]:
clipped_out = np.take(contexts.trajectory, contexts.idx_map + 1, axis=0, mode='clip')
np.place(clipped_out, ~(contexts.idx_map + 1 < len(contexts.trajectory)), np.NAN)

NameError: name 'np' is not defined

In [53]:
clipped_out

array([[[ 1.],
        [ 3.],
        [ 5.]],

       [[ 2.],
        [ 4.],
        [ 6.]],

       [[ 3.],
        [ 5.],
        [ 7.]],

       [[ 4.],
        [ 6.],
        [ 8.]],

       [[ 5.],
        [ 7.],
        [ 9.]],

       [[ 6.],
        [ 8.],
        [10.]],

       [[ 7.],
        [ 9.],
        [11.]],

       [[ 8.],
        [10.],
        [12.]],

       [[ 9.],
        [11.],
        [13.]],

       [[10.],
        [12.],
        [14.]],

       [[11.],
        [13.],
        [15.]],

       [[12.],
        [14.],
        [16.]],

       [[13.],
        [15.],
        [17.]],

       [[14.],
        [16.],
        [18.]],

       [[15.],
        [17.],
        [19.]],

       [[16.],
        [18.],
        [nan]]], dtype=float32)

In [54]:
contexts.data

array([[[ 0.],
        [ 2.],
        [ 4.]],

       [[ 1.],
        [ 3.],
        [ 5.]],

       [[ 2.],
        [ 4.],
        [ 6.]],

       [[ 3.],
        [ 5.],
        [ 7.]],

       [[ 4.],
        [ 6.],
        [ 8.]],

       [[ 5.],
        [ 7.],
        [ 9.]],

       [[ 6.],
        [ 8.],
        [10.]],

       [[ 7.],
        [ 9.],
        [11.]],

       [[ 8.],
        [10.],
        [12.]],

       [[ 9.],
        [11.],
        [13.]],

       [[10.],
        [12.],
        [14.]],

       [[11.],
        [13.],
        [15.]],

       [[12.],
        [14.],
        [16.]],

       [[13.],
        [15.],
        [17.]],

       [[14.],
        [16.],
        [18.]],

       [[15.],
        [17.],
        [19.]]], dtype=float32)