In [9]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [27]:
from kooplearn.data import TrajectoryContexts
import numpy as np

In [44]:
test_traj = np.arange(20, dtype = np.float32)

In [45]:
contexts = TrajectoryContexts(test_traj,
    context_length = 3,
    time_lag = 2)

In [46]:
contexts.idx_map

array([[ 0,  2,  4],
       [ 1,  3,  5],
       [ 2,  4,  6],
       [ 3,  5,  7],
       [ 4,  6,  8],
       [ 5,  7,  9],
       [ 6,  8, 10],
       [ 7,  9, 11],
       [ 8, 10, 12],
       [ 9, 11, 13],
       [10, 12, 14],
       [11, 13, 15],
       [12, 14, 16],
       [13, 15, 17],
       [14, 16, 18],
       [15, 17, 19]])

In [47]:
contexts.idx_map + 1 < len(contexts.trajectory)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False]])

In [51]:
clipped_out = np.take(contexts.trajectory, contexts.idx_map + 1, axis=0, mode='clip')
np.place(clipped_out, ~(contexts.idx_map + 1 < len(contexts.trajectory)), np.NAN)

In [53]:
clipped_out

array([[[ 1.],
        [ 3.],
        [ 5.]],

       [[ 2.],
        [ 4.],
        [ 6.]],

       [[ 3.],
        [ 5.],
        [ 7.]],

       [[ 4.],
        [ 6.],
        [ 8.]],

       [[ 5.],
        [ 7.],
        [ 9.]],

       [[ 6.],
        [ 8.],
        [10.]],

       [[ 7.],
        [ 9.],
        [11.]],

       [[ 8.],
        [10.],
        [12.]],

       [[ 9.],
        [11.],
        [13.]],

       [[10.],
        [12.],
        [14.]],

       [[11.],
        [13.],
        [15.]],

       [[12.],
        [14.],
        [16.]],

       [[13.],
        [15.],
        [17.]],

       [[14.],
        [16.],
        [18.]],

       [[15.],
        [17.],
        [19.]],

       [[16.],
        [18.],
        [nan]]], dtype=float32)

In [54]:
contexts.data

array([[[ 0.],
        [ 2.],
        [ 4.]],

       [[ 1.],
        [ 3.],
        [ 5.]],

       [[ 2.],
        [ 4.],
        [ 6.]],

       [[ 3.],
        [ 5.],
        [ 7.]],

       [[ 4.],
        [ 6.],
        [ 8.]],

       [[ 5.],
        [ 7.],
        [ 9.]],

       [[ 6.],
        [ 8.],
        [10.]],

       [[ 7.],
        [ 9.],
        [11.]],

       [[ 8.],
        [10.],
        [12.]],

       [[ 9.],
        [11.],
        [13.]],

       [[10.],
        [12.],
        [14.]],

       [[11.],
        [13.],
        [15.]],

       [[12.],
        [14.],
        [16.]],

       [[13.],
        [15.],
        [17.]],

       [[14.],
        [16.],
        [18.]],

       [[15.],
        [17.],
        [19.]]], dtype=float32)