In [2]:
%load_ext autoreload
%autoreload 2

In [10]:
from kooplearn.abc import ContextWindow, ContextWindowDataset
from kooplearn.data import TensorContextDataset, MultiTrajectoryContextDataset, multi_traj_to_context

import numpy as np
import torch

In [11]:
xa = torch

traj_lens = [3, 4, 5,6]
trajs = [xa.arange(l, dtype = xa.float32) for l in traj_lens]

In [15]:
single_traj = MultiTrajectoryContextDataset(trajs, context_length=3, time_lag=1)

In [20]:
single_traj.future(1, 5)

ValueError: Invalid number of time_steps=5. Time steps should be greater than 0 and smaller than len(self)=10

In [25]:
torch.cumsum(torch.tensor(lengths), 0)[-1].item()

15

In [23]:
torch.tensor_split(torch.arange(15), torch.cumsum(torch.tensor(lengths), 0)[: -1])

(tensor([0, 1, 2, 3]),
 tensor([4, 5, 6]),
 tensor([7, 8, 9]),
 tensor([10, 11, 12, 13, 14]))

In [17]:
np.split(x, np.cumsum(lengths)[:-1])

[array([0, 1, 2, 3]),
 array([4, 5, 6]),
 array([7, 8, 9]),
 array([10, 11, 12, 13, 14])]

In [9]:
single_traj.future(1, 1)

tensor([[[ 1.],
         [ 2.]],

        [[ 2.],
         [ 3.]],

        [[ 3.],
         [ 4.]],

        [[ 4.],
         [ 5.]],

        [[ 5.],
         [ 6.]],

        [[ 6.],
         [ 7.]],

        [[ 7.],
         [ 8.]],

        [[ 8.],
         [ 9.]],

        [[ 9.],
         [10.]],

        [[10.],
         [11.]],

        [[11.],
         [12.]],

        [[12.],
         [13.]],

        [[13.],
         [14.]],

        [[14.],
         [15.]],

        [[15.],
         [16.]],

        [[16.],
         [17.]],

        [[17.],
         [18.]],

        [[18.],
         [19.]]])

In [46]:
traj.roll(-1)

AttributeError: 'numpy.ndarray' object has no attribute 'roll'

In [45]:
time_steps = 2
traj = np.arange(10)
res = np.roll(traj, 1 - time_steps)
res[1 -time_steps:] = np.nan
res

ValueError: cannot convert float NaN to integer

In [33]:
np.arange(len(traj)) < time_steps - 1

array([False, False, False, False, False, False, False, False, False,
       False])

In [13]:
idmap = single_traj.observables["__idxmap__"]

In [16]:
traj_len = idmap.max() + 1

In [22]:
id_fw = idmap[:, slice(1, None), ...]

In [25]:
single_traj.data.shape

(16, 3, 1)

In [28]:
np.take(traj_np, id_fw + 1, axis = 0)

IndexError: index 20 is out of bounds for axis 0 with size 20

In [4]:
ctx = multi_traj_to_context(traj_torch, observables=observables, context_window_len=2)

/Users/pietronovelli/code_repos/kooplearn/kooplearn/data.py:44: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  cat_data = torch.cat([torch.tensor(ctx.data) for ctx in contexts], dim=0)
/Users/pietronovelli/code_repos/kooplearn/kooplearn/data.py:48: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  [torch.tensor(ctx.observables[obs_name]) for ctx in contexts], dim=0


In [5]:
for k in ctx.observables.keys():
    print(f"{k} -> {ctx.observables[k].shape}")

rand1 -> torch.Size([190, 2, 50, 2])
__idxmap__ -> torch.Size([190, 2, 1])
