In [2]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [3]:
from kooplearn.data import traj_to_contexts, Contexts
import numpy as np

In [4]:
test_traj = np.arange(20)

In [5]:
contexts = traj_to_contexts(test_traj,
    context_window_len = 3,
    lookforward_window_len = 1,
    time_lag = 1)

In [6]:
contexts.data.shape

(18, 3, 1)

In [7]:
print(contexts.evolve_lookback(1))

[[[ 1]
  [ 2]]

 [[ 2]
  [ 3]]

 [[ 3]
  [ 4]]

 [[ 4]
  [ 5]]

 [[ 5]
  [ 6]]

 [[ 6]
  [ 7]]

 [[ 7]
  [ 8]]

 [[ 8]
  [ 9]]

 [[ 9]
  [10]]

 [[10]
  [11]]

 [[11]
  [12]]

 [[12]
  [13]]

 [[13]
  [14]]

 [[14]
  [15]]

 [[15]
  [16]]

 [[16]
  [17]]

 [[17]
  [18]]

 [[18]
  [19]]]
